name: asistente_cobro_isp
description: AplicaciÃ³n para gestionar cobros de ISP de forma local
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: 0.17.0
  charts_flutter: ^0.12.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png